# Generated by Django 2.1 on 2019-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oekaki', '0003_auto_20190909_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='cyclegan/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AlterField(
            model_name='fakeimage',
            name='fake_image',
            field=models.ImageField(upload_to='pix2pix/fake/'),
        ),
    ]
